name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the app code
      uses: actions/checkout@v2

    - name: Set up Python environment & check app.py running
      run: |
        python -m pip install --upgrade pip
        pip install flask
        python app.py


    - name: Build Docker image
      run: |
        IMAGE_TAG="${{ github.sha }}"
        docker build -t $DOCKER_USERNAME/netflix-backend:$IMAGE_TAG .

    - name: Login to Docker Hub
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_TAG="${{ github.sha }}"
        docker push $DOCKER_USERNAME/netflix-backend:$IMAGE_TAG

    - name: Copy application files to EC2
      run: |
        echo "$SSH_PRIVATE_KEY" > mykey.pem
        chmod 600 mykey.pem
        scp -o StrictHostKeyChecking=no -i mykey.pem -r * ubuntu@$EC2_PUBLIC_IP:~/NetflixMovieCatalog/

    - name: Run deployment script on EC2
      run: |
        ssh -i mykey.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
          cd ~/NetflixMovieCatalog
          bash deploy.sh
        EOF
