name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the app code
      uses: actions/checkout@v2

    - name: Set up Python environment & check app.py running
      run: |
        python -m pip install --upgrade pip
        pip install flask
        # Run app.py in the background and wait for it to start
        nohup python app.py &
        sleep 30

    - name: Build Docker image
      run: |
        IMAGE_TAG="${{ github.sha }}"
        docker build -t $DOCKER_USERNAME/netflix-backend:$IMAGE_TAG .

    - name: Login to Docker Hub
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_TAG="${{ github.sha }}"
        docker push $DOCKER_USERNAME/netflix-backend:$IMAGE_TAG

    - name: Copy application files to EC2
      run: |
        echo "$SSH_PRIVATE_KEY" > mykey.pem
        chmod 600 mykey.pem
        scp -o StrictHostKeyChecking=no -i mykey.pem -r * ubuntu@$EC2_PUBLIC_IP:~/NetflixMovieCatalog/

    - name: Deploy Docker image on EC2
      run: |
        ssh -i mykey.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
          # Stop and remove any existing container
          sudo docker stop netflix-backend || true
          sudo docker rm netflix-backend || true
          
          # Pull the latest image
          IMAGE_TAG="${{ github.sha }}"
          sudo docker pull $DOCKER_USERNAME/netflix-backend:$IMAGE_TAG
          
          # Run the new Docker image with environment variable
          sudo docker run -d --name netflix-backend -p 3000:3000 -e MOVIE_CATALOG_SERVICE=http://localhost:8080 $DOCKER_USERNAME/netflix-backend:$IMAGE_TAG
        EOF
